---
- name: Firewall changes
  hosts:  all
  become: true       #as a previlages user 
  tasks:
  - name: Enable a firelwall service 
    firelwalld: 
      service:  ngnix #ngnix services 
      permanent:  true  #chnages would pe permament
      state:  enabled   # sevice state shoukd be enabled or disabled
    notify: 
      -name:  Reload firewalld
  
  handlers:
  - name: Reload firewall             #will reload the firewall services becusae of chnages made in ngnix
    service:
      name: firewalld
      state:  reloaded
